### ISSUE TITLE
使用表单外部变量来替代一部分Hidden字段

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#121]
有个Hidden字段的实质只是个变量，比如FormName或者一些Flags
使用Hidden带来一些麻烦：修改视图、配置权限，实际上这往往是不需要的

这需要的修改主要有（不一定准确，仅供参考）：
渲染界面上，也需要把“变量”渲染成Hidden以此来触发一些公式等

**Comment by yech** [comment]
done & close
