### ISSUE TITLE
"可终止/管理/查看“权限的配置

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#19]
具体参见邮件。

**Comment by gitwang** [comment]
同时还有可查看、可管理权限配置

**Comment by marstone** [comment]
还需配置限定、视图

**Comment by gitwang** [comment]
编辑器支持配置发起/终止/管理/查看权限，OS_WFPOST、OS_WFSTEP、OS_WFSTEPLimit需增加字段 category char(1) not null default 'E'，取值为：'E' -> 执行(包括发起)，'T' ->终止， 'M' ->管理， 'V' ->查看。

视图配置待实现，计算实例的终止/管理/查看限定待实现。

**Comment by gitwang** [comment]
完成实例的终止/管理/查看限定

**Comment by gitwang** [comment]
完成视图配置，OS_WFSTEP表修改字段step为允许null
