### ISSUE TITLE
对于group增加设定“用户只读”

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#25]
UserReadOnly: [true|false] 是否用户只读

**Comment by marstone** [comment]
有些重复字段，仅可由FieldChange改变或者Rendering改变，用户不允许“增／删”

**Comment by marstone** [comment]
统一作为render设置：ReadOnly, Value, Style, Visible, DataSource, [RowVisible]

**Comment by yech** [comment]
除了RowVisible其他几个前端已完成，等待ide配置

**Comment by marstone** [comment]
done
