### ISSUE TITLE
表单支持“连续办理”

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#46]
在步骤上设置“连续办理”，如有多个待办，完成后可显示“下一个”

**Comment by gitwang** [comment]
编辑器已支持设置

**Comment by marstone** [comment]
在doAction接口中，有一定可能会多返回一个step对象（本来也会返回一些，是该流程的后续待办），和其他不同的是：流水号(entry Id)是其他流水的，该步骤即用户可连续办理的步骤。同实例的连续办理上不支持。

**Comment by marstone** [comment]
引擎已支持，但代码要稍后提交。@yech

**Comment by yech** [comment]
前端支持完成。
