### ISSUE TITLE
应用支持来源尤其是对于企业级应用

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#48]
减少第三方提供 /me/apps 的API提供
同源则需设法合并

**Comment by marstone** [comment]
对TaskAPI不透明

**Comment by marstone** [comment]
需TaskAPI做合并：
1.在Engine，定义EnterprsieApp，作为可办的另一个源
2.TaskAPI，对于同源的合并规则：需合并时，仅使用Engine的“推荐”和“图标”

**Comment by yech** [comment]
备忘
infoplus返回的app添加source字段，第三方返回的app根据配置文件自动添加这个source字段
对于同一个source，同一个name的app需要合并。
如果visible＝false那么就不返回了

**Comment by yech** [comment]
done && close
