### ISSUE TITLE
Suggester改进提示和显示

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#55]
1.对于User控件，改进提示，告知用户不仅可以用姓名和拼音，还可以用账号、学工号
（是否还可以提示多个查询条件用逗号分割？）

2.对于同一页的代码，增加显示code做为区分
这个问题遇到过两次：
不同部门下有同名子部门、有些比较大众的名字在同一个部门下也有好多。

**Comment by yech** [comment]
done
