### ISSUE TITLE
渲染界面优化

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#57]
1.多View时显示菜单，根据宽度
2.help是个字段属性，focus＋writable＋desc，悬停在控件后
3.填表页帮助，增加帮助按钮和图层，后台给出用户是否看过help since某个时间点
4.Placeholder for select/suggester
5.提交之后，不要弹出新对话框，沿用旧对话框
6.去掉历史按钮
7.尝试去掉蓝背景和边角
8.提前出现loading动画，html就是loading

**Comment by yech** [comment]
任务已分拆，close
