### ISSUE TITLE
Messenger回填备注信息

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#74]
RT
冲突时，以用户为准？

**Comment by marstone** [comment]
使用配置来支持：
在之前的action是否必填备注的基础上增加为3种选择之一：
备注选项：a）必填 b）选填 c）自定义表达式(或系统指定等字样) ____

**Comment by gitwang** [comment]
在getNextStepsAndPosts方法的返回值中增加了remark一项，为计算好的备注值

**Comment by marstone** [comment]
finished.
