### ISSUE TITLE
流程进度条

### ISSUE THREAD

**Issue by marstone** [infoplus/engine#77]
设置关键步骤的：1.进度名 2.进度值 3.进度组
提供API供前台渲染

**Comment by gitwang** [comment]
In WorkflowManager
    /**
     \* 返回实例的进度
     \* @param instance
     \* @return 完整的进度列表，每一项包含：
     \*          seq：1～10
     \*          title：进度描述
     \*          current：对当前进度点返回true
     \*         结果已按seq排序。
     \* @throws WorkflowException
     */
    List&lt;Map&lt;String, Object&gt;&gt; getMilestones(long instance) throws WorkflowException;

**Comment by yech** [comment]
前端ok

**Comment by marstone** [comment]
done
